#!/bin/sh
rx5-ls "$1" |awk '
BEGIN { mask=1048576 }
/^### 8/ { while(getline>0 && substr($0,1,1)!="#") ; }
$1=="name" { name=substr($0,6,length($0)) }
$1=="pcmstart" { start=$2 }
$1=="loopstart" { lstart=$2 }
$1=="loopend" { lend=$2 }
$1=="pcmend" {
  printf "%6s %7d %7d%s %7d%s %7d%s %7.2f\n", name, start, f(lstart), flag(lstart), f(lend), flag(lend), f($2), flag($2), (f($2)-f(start)-1)/3 }
function f(x) {
  if(x>mask)
    x-=mask
  return x
}
function flag(x) {
  if(x>mask) return "*"
  else return " "
}
'
